# ░░░░░░░░░░░░░░░   PlayerdataPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/playerdataplus.75169/
#  Wiki: https://github.com/momoservertw/PlayerdataPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false
Check-Updates: true

# Format player nicks and make the chat channel more tidy.
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Nick
Nick:
  Enable: false
  Settings:
    # Auto update the nick from database when player joined the game.
    # Need to setup the MySQL settings in CorePlus/data.yml.
    # Changed this option need to restart the server.
    Auto-Update: false
  Limits:
    # Permission: playerdataplus.nick.length.NUMBER | playerdataplus.bypass.nick.length
    Length: 8
    # Prevent players input any color code in their nicks.
    # Bypass permission: playerdataplus.bypass.nick.colorcode
    Prevent-Color-Code: true
    # Prevent players input some bad words in their nicks. Support regular expression.
    # Bypass permission: playerdataplus.bypass.nick.blacklist
    Black-List:
      - fuck
      - bitch
  Formats:
    CMI:
      Enable: false
      # Updating tab list after one player changed their name.
      Update-Tablist: true
      Nick:
        Set: "&%color%%nick%(%player%)"
      Plate:
        Prefix: "&%color%%nick% "
        Suffix: ""
        Color: "WHITE"
    # Changing the Discord member nick if the player account is linked.
    DiscordSRV:
      Enable: false
      Set: "%nick%(%player%)"
    # Executing commands when players changed their nicks.
    Commands: []
    Commands-Clear: []
  # Defining the player"s default nick color.
  # Permission: playerdataplus.nick.group.GROUP
  Groups:
    default:
      Priority: 0
      Color: a
    VIP:
      Priority: 1
      Color: b
    MVP:
      Priority: 2
      Color: d

# Sync the custom player data over multiple servers.
PlayerData:
  Enable: false
  Settings:
    Auto-Save:
      Enable: true
      Interval: 180
      Message: false
    Message:
      Starting: true
      Succeed: true
      Failed: true
  Groups:
    Nick:
      Enable: true
    Custom:
      Enable: true

# Improves server security or fixes some bugs.
# Bypass permission: playerdataplus.bypass.status.TYPE
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Player-Status
Player-Status:
  Enable: false
  Settings:
    Check:
      Schedule:
        Enable: true
        # Unit: tick
        Interval: 100
      Login: true
      World-Change: true
    Features:
      # cmi.command.gm.creative
      # tgod
      CMI: true
      Residence: true
  Fly:
    Enable: true
    # Teleport players to safe location or spawn when disabling fly mode.
    # If there has no save location under to player, he will be teleport to spawn. (Need: CMI)
    Safe-Location:
      Teleport: true
      Commands: []
    Conditions: []
    Location:
      - world
      - world_nether
      - world_the_end
  # Only support CMI.
  God:
    Enable: false
    Conditions: []
    Location:
      - world
      - world_nether
      - world_the_end
  Op:
    Enable: false
    Conditions: []
    Location:
      - world
      - world_nether
      - world_the_end
  # Bypass permission: playerdataplus.bypass.status.gamemode.MODE
  Gamemode:
    Enable: false
    Default: "SURVIVAL"
    Conditions: []
    Location:
      - world
      - world_nether
      - world_the_end

# Cleans expired player data.
# Bypass permission: playerdataplus.bypass.clean
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Clean
Clean:
  Enable: false
  Settings:
    Log: true
    Default:
      Expiration: 60
      Backup: true
  Groups:
    Log:
      Enable: false
      Expiration: 90
      Ignore-List: []
    Region:
      Enable: false
      Residence-Bypass: true
      Ignore-List: []
      #  - "example_world"
      #  - "world(8.8)"
    Playerdata:
      Enable: false
    Advancement:
      Enable: false
    Statistic:
      Enable: false
    AuthMe:
      Enable: false
    CMI:
      Enable: false
    DiscordSRV:
      Enable: false
    MyPet:
      Enable: false
    MyCommand:
      Enable: false
      # To remove the useless variables.
      Playerdata:
        List: []
        Ignore-List: []
    Example:
      Enable: false

# Command: /pdp convert <type> <feature>
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Data-Convertor
Data-Convertor:
  Enable: false
  Offline-To-Online:
    PlayerdataPlus: true
    Playerdata: true
    Advancement: true
    Statistic: true
    AuthMe: true
    CMI: true
    PlayerPoints: true
    NameTagEdit: true
    Residence: true
    LuckPerms: true
  # You need to setup the MySQL settings in CorePlus/config.yml
  Yaml-To-MySQL:
    MyCommand: false
  Return:
    # Return the money and exp to player.
    Bank: true