name: PlayerdataPlus
main: tw.momocraft.playerdataplus.PlayerdataPlus
author: Momocraft
api-version: 1.13
version: 1.0.5
description: Clean the old data and improve the server's performance.
softdepend: [Vault, MythicMobs, CMI, Residence, PlaceHolderAPI, MySQLPlayerDataBridge, SkinsRestorer, ChatControlPro, DiscordSRV, LuckPerms, MyPet]

commands:
  playerdataplus:
    description: Displays main command menu.
    permission: playerdataplus.use
    usage: |
      /playerdataplus
  playerdataplus help:
   description: Shows command menu.
   permission: playerdataplus.help
   usage: |
     /playerdataplus help
  playerdataplus reload:
    description: Reloads all PlayerdataPlus configuration files.
    permission: playerdataplus.command.reload
    usage: |
      /playerdataplus reload
  playerdataplus version:
    description: Checks the plugin version and updates.
    permission: playerdataplus.command.version
    usage: |
      /playerdataplus version
  playerdataplus clean:
    description: Cleans the expired data.
    permission: playerdataplus.command.clean
    usage: |
      /playerdataplus clean

permissions:
  playerdataplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      playerdataplus.use: true
      playerdataplus.command.*: true
      playerdataplus.bypass.*: true
  playerdataplus.use:
    description: Allows use of basic commands.
    default: true
  playerdataplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      playerdataplus.command.reload: true
      playerdataplus.command.version: true
      playerdataplus.command.clean: true
  playerdataplus.command.reload:
    description: Allows use of /playerdataplus command reload.
    default: op
  playerdataplus.command.version:
    description: Allows use of command /playerdataplus version.
    default: op
  playerdataplus.command.clean:
    description: Allowss use of command /playerdataplus clean.
    default: op
  playerdataplus.bypass.*:
    description: Allows player to bypass all features.
    default: op
    children:
      playerdataplus.bypass.clean.*: true
  playerdataplus.bypass.clean.*:
    description: Allows player to bypass all data clean.
    default: op
  playerdataplus.bypass.clean.playerdata:
    description: Allows player to bypass the playerdata clean.
    default: op
  playerdataplus.bypass.clean.advancements:
    description: Allows player to bypass the advancements clean.
    default: op
  playerdataplus.bypass.clean.stats:
    description: Allows player to bypass the stats clean.
    default: op