# ░░░░░░░░░░░░░░░   PlayerdataPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/playerdataplus.75169/
#  Wiki: https://github.com/momoservertw/PlayerdataPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false
Check-Updates: true

General:
  Features:
    # Changed these options need to restart the server.
    Hook:
      AuthMe: true
      CMI: true
      DiscordSRV: true
      FeatureBoard: true
      MyPet: true
      MysqlPlayerDataBridge: true
      PlayerPoints: true
      Residence: true
      SkinsRestorer: true
  MySQL:
    Hostname: "localhost"
    Port: 3306
    Database: "playerdataplus"
    Prefix: ""
    Username: "root"
    Password: ""

#  Format players' nicks and nametag.
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Nick
Nick:
  Enable: false
  Settings:
    Command-Alias: true
  # By default, players cannot color their names or add color codes to their nicknames.
  # Bypass permission: playerdataplus.bypass.nick.colorcode
  Limits:
    # Bypass permission: playerdataplus.bypass.nick.length
    Length: 8
    # Prevent players input some bad words in their nicks. Support regular expression.
    # Bypass permission: playerdataplus.bypass.nick.blacklist
    Black-List:
      - fuck
      - bitch
  Formats:
    Message: "&%color%%nick%(%player%)"
    CMI:
      Enable: false
      Update-Tablist: true
      Nick:
        Set: "&%color%%nick%(%player%)"
      Name-Plate:
        Prefix: "&%color%%nick% "
        Suffix: ""
        # The default color of the player id.
        # Valid: AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE, DARK_RED
        #       GOLD, GRAY, GREEN, LIGHT_PURPLE, RED, WHITE, YELLOW
        Color: "WHITE"
    # Changing the Discord member nick if the player account is linked.
    DiscordSRV:
      Enable: false
      Set: "%nick%(%player%)"
    # Executing commands when players changed their nicks.
    Commands: []
    Commands-Clear: []
  # Defining the player"s default nick color.
  # Permission: playerdataplus.nick.group.GROUP
  Groups:
    default:
      Priority: 0
      Color: a
    VIP:
      Priority: 1
      Color: b
    MVP:
      Priority: 2
      Color: d

# Sync the custom player data over multiple servers.
PlayerData:
  Enable: false
  Settings:
    Auto-Save:
      Enable: true
      Interval: 180
      Message: false
    Message:
      Starting: true
      Succeed: true
      Failed: true
  Groups:
    Nick:
      Enable: true
    Custom:
      Enable: true

# Auto change player status like "disable fly status".
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Player-Status
Player-Status:
  Enable: false
  Settings:
    Check:
      Schedule:
        Enable: true
        # Unit: tick
        Interval: 100
      Login: true
      World-Change: true
  Op:
    Enable: false
    Location:
      - world
      - world_nether
      - world_the_end
  Fly:
    Enable: false
    # Teleport players to safe location or spawn when disabling fly mode.
    Safe-Location:
      Teleport: true
      Commands:
        - "console: cmi spawn %player%"
    Location:
      - world
      - world_nether
      - world_the_end
  # Only support CMI.
  God:
    Enable: false
    Location:
      - world
      - world_nether
      - world_the_end
  # Bypass permission: playerdataplus.bypass.status.gamemode.MODE
  Gamemode:
    Enable: false
    Default: "SURVIVAL"
    Location:
      - world
      - world_nether
      - world_the_end

# Cleans expired player data.
# Bypass permission: playerdataplus.bypass.clean
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Clean
Clean:
  Enable: false
  Settings:
    Log: true
    Default:
      Expiration: 60
      Backup: true
  Groups:
    Log:
      Enable: false
      Expiration: 90
      Ignore-List: [ ]
    Region:
      Enable: false
      Residence-Bypass: true
      Ignore-List: [ ]
      #  - "example_world"
      #  - "world(8.8)"
    Playerdata:
      Enable: false
    Advancement:
      Enable: false
    Statistic:
      Enable: false
    AuthMe:
      Enable: false
    CMI:
      Enable: false
    DiscordSRV:
      Enable: false
    MyPet:
      Enable: false
    MyCommand:
      Enable: false
      # To remove the useless variables.
      Playerdata:
        List: [ ]
        Ignore-List: [ ]
    Example:
      Enable: false

# Command: /pdp convert <type> <uuid1> <uuid2>
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Data-Convertor
User-Convertor:
  Enable: false
  Groups:
    # CMI features: Money, Nick, Home, Inventory, EnderChest.
    CMI: true
    PlayerPoints: true
    MyPet: true
    MySuite: true
    Residence: true
    LuckPerms: true