# ░░░░░░░░░░░░░░░   PlayerdataPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/playerdataplus.75169/
#  Wiki: https://github.com/momoservertw/PlayerdataPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 4
Debugging: false

# Format player nicks and make the chat channel more tidy.
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Nick
Nick:
  Enable: false
  Settings:
    # Auto update the nick from database when player joined the game.
    # Need to setup the MySQL settings in CorePlus/config.yml
    Auto-Update: true
  Limits:
    # Permission: playerdataplus.nick.length.NUMBER | playerdataplus.bypass.nick.length
    Length: 8
    # Prevent players input any color code in their nicks.
    # Bypass permission: playerdataplus.bypass.nick.colorcode
    Prevent-Color-Code: true
    # Prevent players input some bad words in their nicks. Support regular expression.
    # Bypass permission: playerdataplus.bypass.nick.blacklist
    Black-List:
      - fuck
      - bitch
  Formats:
    CMI:
      Enable: false
      # Updating tab list after one player changed their name.
      Update-Tablist: true
      Set: "&%color%%nick%(%player%)"
      Clear: "&%color%%player%"
    NameTagEdit:
      Enable: false
      Set:
        Prefix: "&%color%%nick% &f"
        Suffix: ""
      Clear:
        Prefix: "&%color%"
        Suffix: ""
    # Executing commands when players changed their nicks.
    Commands: []
    Commands-Clear: []
  # Defining the player"s default nick color.
  # Permission: playerdataplus.nick.group.GROUP
  Groups:
    # Priority is top to bottom.
    default: a
    VIP: b
    MVP: d

# Controls player status to improve the gaming experience or fixed.
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Player-Status
Player-Status:
  Enable: false
  Settings:
    Schedule:
      Interval: 100
  Fly:
    Enable: false
    Settings:
      CMI:
        tfly: true
        cfly: true
      Residence: true
    Disabled:
      Enable: true
      Check:
        Schedule: true
        Login: true
        World-Change: true
      # Teleport players to save location when canceled the fly mode.
      Teleport:
        Enable: true
        Spawn:
          Force: false
          World: world
          X: 0
          Y: 0
          Z: 0
          Pitch: 0
          Yaw: 0
      Permissions:
        - cmi.command.fly
      Location:
        - world
        - world_nether
        - world_the_end
    Enabled:
      Enable: true
      Ignore:
        Permissions:
          - cmi.command.fly
      Location:
        - world
        - world_nether
        - world_the_end
      Check:
        Schedule: false
        Login: true
        World-Change: true
  God:
    Enable: false
    Ignore:
      Permission:
        - cmi.command.god
      CMI:
        tgod: true
    Location:
      - world
      - world_nether
      - world_the_end
  Op:
    Enable: false
    Ignore:
      Permission:
        - playerdataplus.bypass.status.op
    Location:
      - world
      - world_nether
      - world_the_end
  Gamemode-Survival:
    Enable: false
    Default: "Survival"
    Ignore:
      Permissions:
        - cmi.command.gm.survival
    Location: [ ]
  Gamemode-Creative:
    Enable: true
    Default: "Survival"
    Ignore:
      Permissions:
        - cmi.command.gm.creative
    Location: [ ]
  Gamemode-Adventure:
    Enable: true
    Default: "Survival"
    Ignore:
      Permissions:
        - cmi.command.gm.adventure
    Location: [ ]
  Gamemode-Spectator:
    Enable: true
    Default: "Survival"
    Ignore:
      Permissions:
        - cmi.command.gm.spectator
    Location: [ ]

# Cleans the old player data.
# Bypass permission: playerdataplus.bypass.clean
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Clean
Clean:
  Enable: false
  Settings:
    Auto-Clean:
      Enable: false
    Log: true
    Backup:
      File:
        Path: "plugins//PlayerdataPlus//Backup"
        Zip: false
      # Needed to setup in CorePlus's data.yml.
      MySQL:
        Enable: true
    # The default setting of groups.
    Default:
      Expiration: 60
      Backup: true
  Groups:
    Log:
      Enable: false
      Expiration: 90
      Ignore-List: []
    Region:
      Enable: false
      Residence-Bypass: true
      Ignore-List: []
      #  - "example_world"
      #  - "world(8.8)"
    Playerdata:
      Enable: false
    Advancement:
      Enable: false
    Statistic:
      Enable: false
    AuthMe:
      Enable: false
    CMI:
      Enable: false
    DiscordSRV:
      Enable: false
    MyPet:
      Enable: false
    MyCommand:
      Enable: false
      # To remove the useless variables.
      Playerdata:
        List: []
        Ignore-List: []
    Example:
      Enable: false


# Command: /pdp convert <type> <feature>
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Data-Convertor
Data-Convertor:
  Enable: false
  Offline-To-Online:
    PlayerdataPlus: true
    Playerdata: true
    Advancement: true
    Statistic: true
    AuthMe: true
    CMI: true
    PlayerPoints: true
    NameTagEdit: true
    Residence: true
    LuckPerms: true
  # You need to setup the MySQL settings in CorePlus/config.yml
  Yaml-To-MySQL:
    MyCommand: false
  Return:
    # Return the money and exp to player.
    Bank: true

Message:
  prefix: "&7[&dPlayerdataPlus&7]&r "
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lPlayerdataPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩"
    help: "&f/pdp help &8- &7This help menu."
    reload: "&f/pdp reload &8- &7Reload config file."
    version: "&f/pdp version &8- &7Checks the plugin version and updates."
    clean: "&f/pdp clean <type> &8- &7Clean the expired data."
    nick: "&f/pdp nick <nick/color/off> &8- &7Change the nick name. /n &fcolor: &aa&8, &bb &7(VIP)&8, &dd &7(MVP) /n &foff: clear the nick"
    nickOther: "&f/pdp nick <nick/color/off> [player] &8- &7Change the nick name for a player. /n &fcolor: &aa&8, &bb &7(VIP)&8, &dd &7(MVP) /n &foff: clear the nick"
  Nick:
    invalidLength: "&cYour nick is too long. Max &6%nick_length% &esymbols."
    invalidLengthTarget: "&c%targetplayer%''s Nick is too long. Max &6%nick_length% &esymbols."
    invalidNick: "&cYour nick contains illegal characters."
    invalidNickTarget: "&c%targetplayer%''s nick contains illegal characters."
    invalidColor: "&cYou don''t have permission to set this color."
    invalidColorTarget: "&c%targetplayer% don''t have permission to set this color."
    invalidColorInside: "&cYou can''t use color code inside the nick."
    invalidColorInsideTarget: "&c%targetplayer% can''t use color code inside the nick."
    change: "&fYour new nick &8- &%color%%nick%(%player%)"
    changeTarget: "&f%targetplayer%''s new nick &8- &%color%%nick%(%player%)"
    clear: "&fYour new nick &8- &%color%%player%"
    clearTarget: "&f%targetplayer%''s new nick &8- &%color%%player%"
    changeColor: "&fYour new nick color &8- &%color%❤"
    changeColorTarget: "&f%targetplayer%''s new nick color &8- &%color%❤"
  Clean:
    succeed: "%prefix% &eRemoved a total of: &7%amount% &e(%value%&e)"
    listed: "%prefix% &eListed a total of: &7%amount% &e(%value%&e)"
    start: "%prefix% &6Start checking player data..."
    end: "%prefix% &6Clean process has ended."
      start: "%prefix% &6Start checking player data..."
    toggleOn: "%prefix% &aEnabled the clean process."
    toggleOff: "%prefix% &cDisabled the clean process."
    alreadyOn: "%prefix% &fThe clean process has already enabled."
    alreadyOff: "%prefix% &fThe clean process has already disabled."