# --{ =-=-=-=-=-=-=-=-=-= PlayerdataPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 3
# If you want to see if the player data is out of date or bypassed, you can turn on the Debug mode.
Debugging: false
Check-Updates: true

# Clean the old data and improve the server's performance.
# Player bypass permission: playerdataplus.bypass.clean
Clean:
  Settings:
    Expiry-Days: 60
    # Create a detail log file in plugin folder.
    Log: true
    # It will clean up a limited amount of data once and then restart the clean process again. Set "0" to disable this feature.
    Max-Clean-Per-Data: 10000
    # If your "timeout-time" setting in spigot.yml is too low, it may cause the server to restart in the middle of cleaning.
    # Please set a higher number of seconds based on the number of server players, especially for the first time.
    Timeout-Warning: true
    # Automatic clean the old data when the server is starting.
    Auto-Clean:
      Enable: false
      Delay: 20
    # Backup the data in plugin folder, it only support some data types.
    Backup:
      Enable: true
      # The backup folder: plugin, custom
      Mode: 'plugin'
      Folder-Name: 'Backup'
      # Custom the backup path like "C:\Server". You need to set the Backup Mode to "custom".
      Custom-Path: 'C:\Server'
      To-Zip: true
  Control:
    Logs:
      Enable: false
      # You can specific the expiry day for each data.
      Expiry-Days: 90
      # You can disable the backup feature for each data.
      Backup: true
    # Bypass permission: playerdataplus.bypass.clean.* or playerdataplus.bypass.clean.playerdata
    Playerdata:
      Enable: false
    Advancements:
      Enable: false
    Stats:
      Enable: false
    Regions:
      Enable: false
      # Bypass clean the regions which contain Residences.
      # If you disable this option, you can still add the custom flag "bypassclean" to the residences to bypass the clean event.
      Residence-Bypass: true
      Worlds:
        - world
        - world_nether
        - world_the_end
      Ignore-Regions: []
      #  - 'world 8.8'
    AuthMe:
      Enable: false
    CMI:
      Enable: false
    DiscordSRV:
      Enable: false

# Format players' nicks and make chat messages more tidy.
# Commands: /playerdataplus nick [color] [bypass] [player]
# More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Commands
Nick:
  # The rule of nicks.
  Limits:
    # The input custom nick length. It does not include the regular formats in the configuration.
    # Bypass permission: playerdataplus.bypass.nick.length
    Length: 8
    # Prevent players input any color code in their nicks.
    # Bypass permission: playerdataplus.bypass.nick.purecolor
    Pure-Color: true
    # Prevent players input some bad words in their nicks.
    # Bypass permission: playerdataplus.bypass.nick.blacklist
    Black-List:
      - fuck
      - bitch
    # Formatting the nicks and adding player id in their nicks.
    Formats:
      CMI:
        Enable: false
        # Updates the player names in the tablist.
        Tablist-Update: true
        # The format of nick when players changed their nicks.
        On: "&%color%%nick%(%player%)"
        # The format of nick when players canceled their nicks.
        Off: "&%color%%player%"
      NameTagEdit:
        Enable: false
        On:
          Prefix: "&%color%%nick% &f"
          Suffix: ""
        Off:
          Prefix: "&%color%"
          Suffix: ""
      # Executed custom commands when players changed their nicks.
      # More information: https://github.com/momoservertw/PlayerdataPlus/wiki/Custom-Commands
      Commands: []
      #  - /nick &%nick_color%%nick%(%player%)
      Commands-Off: []
      #  - /nick &%nick_color%%player%
    # Define the player's default nick color.
    # Permission: playerdataplus.nick.group.GROUP
    Groups:
      # The default nick color if player doesn't have any permission.
      Default: "a"
      # The default nick color for a player who has color permission. The highest number of group name will be chosen.
      Custom:
        0: "a"
        1: "b"
        2: "d"
        3: "e"
    # The input words of colors when players are using commands to custom their nicks' color.
    # For example, /playerdataplus nick MyNick green
    # Permission: playerdataplus.nick.color.COLOR
    Colors:
      Correspond:
        a: "green"
        b: "aqua"
        c: "red"
        d: "light_purple"
        e: "yellow"
        f: "white"
        0: "black"
        1: "dark_blue"
        2: "dark_green"
        3: "dark_aqua"
        4: "dark_red"
        5: "dark_purple"
        6: "gold"
        7: "gray"
        8: "dark_gray"
        9: "blue"

Message:
  prefix: '&7[&dPlayerdataPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/playerdataplus help &cfor a list of commands.'
  targetNotOnline: '&cPlayer &e%targetplayer% &cdoesn''t online!'
  PlayerdataPlus:
    Commands:
      title: '&8▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lPlayerdataPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩'
      help: '&a/playerdataplus help &8- &7This help menu.'
      reload: '&a/playerdataplus reload &8- &7Reload config file.'
      clean: '&a/playerdataplus clean &8- &7Clean the expired data.'
      nick: '&a/playerdataplus nick <nick> [color] &8- &7Change your nick name. /n &cColor: &aa &8| &bb &8(VIP) &8| &dd &8(MVP) &8| &ee &8(GOD)'
      nickOff: '&a/playerdataplus nick off &8- &7Clear your nick name.'
      nickOther: '&a/playerdataplus nick <nick> [color] [bypass] [player] &8- &7Change other players'' nick name. /n &cColor: &aa &8| &bb &8(VIP) &8| &dd &8(MVP) &8| &ee &8(GOD)'
      nickOffOther: '&a/playerdataplus off [player] &8- &7Clear other players'' nick name.'
    Nick:
      invalidLength: '&cNick is too long. Max &6%nick_length% &esymbols.'
      targetInvalidLength: '&c%targetplayer% nick is too long. Max &6%nick_length% &csymbols.'
      invalidNick: '&cYou can''t use this nick name.'
      targetInvalidNick: '&c%targetplayer% can''t use this nick name.'
      invalidColor: '&cYou don''t have permission to set this color.'
      targetInvalidColor: '&c%targetplayer% don''t have permission to set this color.'
      invalidColorInside: '&cYou can''t set this color inside the nick.'
      targetInvalidColorInside: '&c%targetplayer% can''t set this color inside the nick.'
      successOn: '&aYou nick is: &%nick_color%%nick%(%player%)'
      targetSuccessOn: '&a%targetplayer% nick is: &%nick_color%%nick%(%player%)'
      successOff: '&aYou nick is: &%nick_color%%player%'
      targetSuccessOff: '&a%targetplayer% nick is: &%color%%player%'